export const NS_AUTH = 'auth';

export const DO_LOGIN = 'DO_LOGIN';
export const LOGOUT = 'LOGOUT';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_FORGOT_PASSWORD = 'RESET_FORGOT_PASSWORD';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const SAVE_AUTH_DATA = 'SAVE_AUTH_DATA';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const GET_QR_CODE = 'GET_QR_CODE';
export const SET_QR_CODE = 'SET_QR_CODE';

export const VERIFY_2FA_CODE = 'VERIFY_2FA_CODE';
export const DISABLE_2FA = 'DISABLE_2FA';

export const CLEAR_AUTH_DATA = 'CLEAR_AUTH_DATA';

export const GET_USER_IP_ADDRESS = 'GET_USER_IP_ADDRESS';

// Dynamic fill data
export const SET_FILL_USERNAME = 'SET_FILL_USERNAME';
export const RESET_FILL_USERNAME = 'RESET_FILL_USERNAME';

export const DO_REGISTER = 'DO_REGISTER';
export const VERIFY_MAIL = 'VERIFY_MAIL';
export const SET_TOKEN_REGISTER = 'SET_TOKEN_REGISTER';
export const SET_MESSAGE_VERIFY_MAIL = 'SET_MESSAGE_VERIFY_MAIL';

export const GET_AVAILABLE_BALANCE = 'GET_AVAILABLE_BALANCE';
export const SET_AVAILABLE_BALANCE = 'SET_AVAILABLE_BALANCE';

export const TRANSFER_BET_TO_ANOTHTER = 'TRANSFER_BET_TO_ANOTHTER';
export const WITHDRAW_ACTION = 'WITHDRAW_ACTION';

export const GET_DEPOSIT_ADDRESS = 'GET_DEPOSIT_ADDRESS';
export const SET_DEPOSIT_ADDRESS = 'SET_DEPOSIT_ADDRESS';
